/* provider */
variable "region"               {}
variable "access_key"           {}
variable "secret_key"           {}
variable "vpc_id" {}
variable "igw_id" {}
variable "sbn_id" {}
variable "rt_name" {}
variable "rt_cidr" {}